### ISSUE TITLE
PreFile window appears blank

### ISSUE THREAD

**Issue by hcshires** [slimit75/xACARS#4]
When I go to open Prefile after selecting my bid, a new window pops up, but nothing is rendered in it

Please tell us how to reproduce the issue.
1. Select a Bid
2. Click "Prefile"
3. Observe nothing is there

**Expected behavior**
When opening the Prefile window, content should appear

![image](https://user-images.githubusercontent.com/25646224/88348321-ba7bc380-cd12-11ea-852f-008f44fce5b8.png)

**Versions**
Please fill out below
 - Windows 10
 - 1.0.0-alpha2
 - FSX

**Comment by slimit75** [comment]
Hello!

Do you know if your virtual airline is using phpVMS v5 or phpVMS v7?

**Comment by hcshires** [comment]
v7

**Comment by hcshires** [comment]
I managed to fix the issue. It was a bad call to the wrong API GET request. /bids does not have a subfleet array where as /flights/{flight id} does. I simply got the flight id from the bid and then grabbed the list of aircraft from the specified flight.
![image](https://user-images.githubusercontent.com/25646224/88448086-787c7b80-cdff-11ea-9607-b0f3840d96c3.png)

**Comment by hcshires** [comment]
Do you mind telling me how you build the exe so I can test the rest of the ACARS with my fix?

**Comment by hcshires** [comment]
Also could you send me how to install pyuipc 0.4? It can't find my current module and it says that all of its functions don't exist

**Comment by slimit75** [comment]
Sorry for the late reply. I dont exactly remember how I built it as an exe, I believe it was with  [pyinstaller/pyinstaller](https://github.com/pyinstaller/pyinstaller). To download pyuipc, you can get it from the [FSUIPC SDK](http://www.fsuipc.com/)

**Comment by hcshires** [comment]
No worries. My issue is not finding a download, but actually making it
work. Your requirements.txt says 0.4 and I'm not sure if the current (0.6)
works or not, or if it's just my way of installing it. Do you mind
describing how you got your installed and recognized by py?

**Comment by slimit75** [comment]
0.6 should work, however I haven't tested it myself. In terms of how I got pyuipc, I think I just ran the installer. If I remember correctly however, it requires Python 32-bit.

**Comment by hcshires** [comment]
I did both of those things (assuming any version of python is fine and anaconda is not an issue) and py.exe returns an error saying none of the functions from pyuipc exist. Do you know what's causing that/how to fix this?

**Comment by slimit75** [comment]
Are you installing it for the correct python version?

**Comment by hcshires** [comment]
What version would that be? I've tried 32bit with anaconda for 3.8, 3.7, 3.5, and 2.7

**Comment by slimit75** [comment]
Hmm, I would think one of those work. Can you try pyuipc 0.5?

**Comment by hcshires** [comment]
No change in result. What directory is yours installed in? The more specific the better.

**Comment by hcshires** [comment]
Ok, so I ran a code snippet that returns if the pyuipc module is found. 0.6 currently exists, but for some reason, it's methods do not. Idk if that helps lol
`import importlib
spam_spec = importlib.util.find_spec("pyuipc")
found = spam_spec is not None
print(found)`

**Comment by hcshires** [comment]
Maybe it has to do with the type of spacing? Is pyuipc written with spaces or tabs?

**Comment by hcshires** [comment]
I fixed it! The python execution was conflicting with anaconda. It works now. Thanks for you help!
